Update build-docset.yml

diff --git a/.github/workflows/build-docset.yml b/.github/workflows/build-docset.yml
--- a/.github/workflows/build-docset.yml
+++ b/.github/workflows/build-docset.yml
@@ -29,9 +29,47 @@ jobs:
           ref: ${{ steps.DRFLatestRelease.outputs.release }}
           path: .build
       - name: Build Docset
+        env:
+          DOC_VERSION: ${{ steps.DRFLatestRelease.outputs.release }}
+          DOCSET_NAME: "django-rest-framework-${{ steps.DRFLatestRelease.outputs.release }}.docset"
+          DOCSET_DIR: "Dash-User-Contributions/docsets/Django_REST_Framework"
+          DOCSET_VER_DIR: "${DOCSET_DIR}/versions/${{ steps.DRFLatestRelease.outputs.release }}"
         run: |
           cd .build
           # force using file urls
           echo "use_directory_urls: false" >> mkdocs.yml
           pipenv run mkdocs build --clean
+          mkdir -p ${DOCSET_NAME}/Contents/Resources/Documents
+          cp -Rf django-rest-framework/site/* ${DOCSET_NAME}/Contents/Resources/Documents/
+
+          cat << EOF > ${DOCSET_NAME}/Contents/Info.plist
+<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+<plist version="1.0">
+  <dict>
+    <key>CFBundleIdentifier</key>
+    <string>drf</string>
+    <key>CFBundleName</key>
+    <string>Django REST framework</string>
+    <key>DocSetPlatformFamily</key>
+    <string>django</string>
+    <key>isDashDocset</key>
+    <true/>
+    <key>dashIndexFilePath</key>
+    <string>index.html</string>
+    <key>isJavaScriptEnabled</key>
+    <true/>
+  </dict>
+</plist>
+EOF
+          pipenv run python ../drfdoc2set.py ${DOC_VERSION} && tar --exclude='.DS_Store' -czf django-rest-framework-${DOC_VERSION}.tgz ${DOCSET_NAME} && echo " done."
+          cp -vfp django-rest-framework-${DOC_VERSION}.tgz ${DOCSET_DIR}/django-rest-framework.tgz
+          mkdir -p ${DOCSET_VER_DIR}
+          cp -vfp django-rest-framework-${DOC_VERSION}.tgz ${DOCSET_VER_DIR}/django-rest-framework.tgz
+
+            # cd ${WORKING_DIR}/build/Dash-User-Contributions
+#             if [ ! -f docsetcontrib.tgz ]; then
+#               wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz
+#             fi
+#             tar -xzf docsetcontrib.tgz && ./docsetcontrib --verify && echo "docset is good" || echo "verify failed"; exit 1
 
